### ISSUE TITLE
its not an issue but...

### ISSUE THREAD

**Issue by Micocono123** [Nicbo/InvadedLandsEvents#12]
hi i really liked the plugin! best event plugin i found for free! but i would like it if u could make it work on 1.16.5 please

**Comment by Nicbo** [comment]
Thanks for the feedback! There is an alpha release out right now that supports 1.8-latest, with a bunch of new features. Let me know if you experience any issues w/ it : ) https://github.com/Nicbo/InvadedLandsEvents/releases/tag/v2.0.0-ALPHA.1.
